apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Config: deployment-configuration/profiles/dev/messaging (Flux profile-config)
  - mailpit-storage.yaml
  - mailpit.yaml
  - mailhog.yaml
  - inbucket.yaml
