apiVersion: ENC[AES256_GCM,data:w2Y=,iv:Cp20jKCOTwsFGNGijHyzxjjvgaONRD3TORobKGgH3Pk=,tag:7aX9i0VgevYYyrmIeY3RbA==,type:str]
kind: ENC[AES256_GCM,data:ga8YX0hB,iv:oz67hqx/b82XNCTv6K/CdZVyEXjRdlrW9sL+4Nwk2Bs=,tag:KoiRCmebiV4zA/i2AgcJFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZH3/LozYcwIumFv5/TKtnqbRs1pH3A==,iv:ccJfGkyA3XEQ03pYipymhNpbKNhEq4Z0Hl/m8tSn+do=,tag:gr90RD7bK4SkZnWq20gWJQ==,type:str]
    namespace: ENC[AES256_GCM,data:wohdZ6JTYeUmwMyXtEE=,iv:zmWPpFO1ryIKfXnVR/2szTo0EWwtR1Rzbh9HbO5PSno=,tag:NdLOXwSeUUy+eOuYjTiZ+Q==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:7QG30+NrrgAMjEXMoGPa5CwRkuoih3IuUw==,iv:OdkG8xjVSGLYf0k7x7x9Wtzpnzx8LFjrxqdwVv0iwic=,tag:f7s7koWzgcJqXKw2IZsMnw==,type:str]
        gitops.microscaler.io/stack: ENC[AES256_GCM,data:72LOY6D59bTx7amyx/E=,iv:xY/hPFWhnFkLWe6mudqgLaDoTaQb7wcBFbEKbu1kdtA=,tag:3NgvXVhee6shaI1naT/hzg==,type:str]
type: ENC[AES256_GCM,data:gW0KT9IY,iv:CfBi2CvqzdwjuAex6HPgwufBzkqOY7IVgmZ/SkzpeTY=,tag:ZQZw3EYmnH5zuYx2KOKPdQ==,type:str]
data:
    id_ed25519: ENC[AES256_GCM,data:ENUAkXInIzzE5wYjG0eOpbrDnCr8k9YVJraocmKFbAL2afh9PrBk5+Rn7R4XyZxjVyIVdbdgyyyfIxCoiUIiffufijuL4ZS7UX0ynl+tLzAu8LKmI6S2CTOFc2dFrXHSYC6zMLL79b64Sd4mbkyXBjTeONICA/4/gRXdja3aORKLwn7RS3QD9ipgGflwA9ywK/BMBxQZQzrYSDXsdKAp9iK9k22Ss7TwsfhR1stzPgrXDlN0SNv4dWP67dqqyYGWqPt2dSA1SfZa2PVPK6otY3p011sWeHD4Xa/M4yXBGmTggFWcjzetkkEMv7FiuCRVNPVx9PhUvzJMYZt+RVymObLLKrwcM7OvmrYr9X17TMLxpEw98Ek95UAc/yjhWMX50xQvwDc9oprge8HeL88txqq9mWXctb9fD8egorAyg32sCJNVPfW49JG1pyF6WecIHwZZui/EXNrk2v3EbPefLyq2+Kn5KhI/srIVBd7wL1RUM8Zejdt0e1jzQS6J6pjJ6sEBYDWjAp5xF+WlJ12ycMZ6Po2qMYuFrO5EsNPTtlt374kmJqed5Gn+2Zfi85w6O+Vg1t5VYy3+EVl3CxUUQADdAfolaR/HJaR6bIYDynLdwa0tnznff18X9n71GBE5+uvCAsIfpNWaGYVkAbLimVEJHjjr/FUWY+ZmX8UdvZhfWzjd7ALlZKZfsoPdWW7WlaGEKVhi9BcXg5W9eEJ3rdryc09G+hrSfapu7W6F38M=,iv:lGfxaaYafL1xYNL0Wb2g8M6VVwV2mBUIRCv4KskSrsI=,tag:SggVRpCL/iqfCsZIUh3Tig==,type:str]
sops:
    age:
        - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTC9IbDRRcFVJSGRIejZP
            VnhWSlRvRkdKMUNTSEZnMUpGakpJUTBPNUUwCmtHUFZ4ZTFCUDZpSWJvcDkwODdx
            RElkaTF4VXR3M2FRQWk4aDdvOHNxWTgKLS0tIDNuenlhYW9weW9FZWxPYXkwb3dN
            TzdwTEVwK25RYjMrbFNwSXBGN2tibkEKvoHN2ADMW+MH410AcTFjPcha0m0lv1MB
            s5/NLK5B5xkaUUjAhwggIFW/s+0TV7jr9yMXJ6pxdvcgDLKnG7kP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T22:16:00Z"
    mac: ENC[AES256_GCM,data:7bbSyoX7TF4Zdi1jhXwXbhnMHuB993vY4/YeNLnA23HROD+sNWKbkc0oX8+I3xwquAZoR8VEcRJR0ljOBbYR+mqMBgSzzC+Z4b15lY1SnOCJs/FCsnpJ1vn94tmujJAq1Z2fYzlVPcrHz/L2lGRy7gdjinqgthYf3xWDF0qoWtI=,iv:YAp7Bzc56YKiW9cpRjAGJzWMQtT1pEE1MvQjg53Xj/E=,tag:G6IGqluSuRlL9sxCKRVE+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
