apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-local-path-retain.yaml
  - helmrepository.yaml
  # Secrets: deployment-configuration/profiles/dev/postgres-ha (Flux profile-secrets)
  - helm-release.yaml
  - postgres-lb-service.yaml
