apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helm-release.yaml
  - envoyproxy.yaml
  - gatewayclass.yaml
  - gateway.yaml
  - referencegrant-tls.yaml
  - httproutes/hauliage.yaml
  - httproutes/opensearch.yaml
  - httproutes/tilt-hosts.yaml
