apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# staging control — same shape as dev; GitOpsSet patch points at staging inventory
resources:
  - ../../../root/controllers/gitopssets
  - ../../../root/gitopssets
patches:
  - target:
      kind: GitOpsSet
      name: platform-stacks
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/generators/0/gitRepository/directories/0/path
        value: gitops/clusters/staging/inventory/stacks/*
