apiVersion: v1
kind: Service
metadata:
  name: freeradius
  namespace: cylon
  labels:
    app: freeradius
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.177.76.223"
spec:
  type: LoadBalancer
  ports:
    - port: 1812
      name: auth
      protocol: UDP
    - port: 1813
      name: acct
      protocol: UDP
  selector:
    app: freeradius
