apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Config: deployment-configuration/profiles/dev/imgproxy (Flux profile-config)
  - helmrepository.yaml
  - helm-release.yaml
