---
- name: reload user systemd
  become: true
  become_user: "{{ tilt_user_units_operator }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ tilt_user_units_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ tilt_user_units_uid }}/bus"
