apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

configMapGenerator:
  - name: messaging-config
    envs:
      - application.properties
  - name: messaging-helm-values-mailpit
    files:
      - values.yaml=helm-values-mailpit.yaml

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
