# Encrypted: application.secrets.env (SOPS age). Secret: data/minio-credentials
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

secretGenerator:
  - name: minio-credentials
    envs:
      - application.secrets.env

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
