apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - clusterissuer-bootstrap.yaml
  - certificate-ca.yaml
  - clusterissuer-ca.yaml
  - certificate-wildcard.yaml
