apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

configMapGenerator:
  - name: postgres-backup-config
    envs:
      - application.properties

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
