apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cylon

configMapGenerator:
  - name: routellm-config
    envs:
      - application.properties

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
