apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
  labels:
    app.kubernetes.io/part-of: shared-gitops-k8s-cluster
    gitops.microscaler.io/stack: airflow
type: Opaque
stringData:
  fernet-key: ENC[AES256_GCM,data:3L0u+IIusnk00HtdUgRuUEy9zUuztGcEKI7A4G1XjPGWQW7vtCtqKneRQB4=,iv:ZWyX1k1M2qWd6EC1eoMlvZ6aHGSSpjDBpX/VElPpdsg=,tag:iaHp4ZfjWOpxo4dUK/K9mw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdVdobDdzR0VaVXo0bUQw
      eVhoYzRiUVZ4QlQzYktZRkVpK2RaMEwrRFhVCmRsT2dzWFZhNXVkNDhGVUtlZ0pK
      MHpYREJxbVV0N05ITUw4S3p6UEl6bFkKLT4gejFMdyFZZEwtZ3JlYXNlCmZQRHBv
      czROZVRtaHVRRmtqNlQxcHQxcFFWZFFmdjNrY2JuRml2eDRvNW5BMmVZRUMyNk00
      VFp4Ulo5T3ZpZ3UKU3NXU1U4eThXbzlGaGgwCi0tLSBNc2hSTENlTllMbDN2dDI2
      aEUxTG5oSmhCaWNCT2ZRL0hqVHl2QjF6OWtrCq8zqEzNArcnMY8sqJvD3Aonu3/N
      E1WNd9duND4A30/3NvP2yYcVsdAMje1wPQvwMVZdsj11FUrIwm5gTxxzQNE=
      -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-08-07T12:52:00Z'
  mac: ENC[AES256_GCM,data:EDdAT2loRnTWSQw00zeqvYClXx8alO7rtA51dDJ15ClA0Ce1x3fCbK5eSTTMeuboHs1y3cX7HgM5DbD3H6taW9tUNx5qgMwNt6sROSYX3lI2hPTeVMnJZ00LUg/9E14I81xJ+u8lDOU9t6Gh9alUmvUqr8qAL1LBGIXnDQT2Fr8=,iv:SHOHY7PNmWD6Vi+LinF/y1TqrjZB9UWZjQeYvL3QEuA=,tag:uOYljW53hc3lY3rcUBxjaQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
