apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  namespace: airflow
  labels:
    app.kubernetes.io/part-of: shared-gitops-k8s-cluster
    gitops.microscaler.io/stack: airflow
type: Opaque
stringData:
  connection: ENC[AES256_GCM,data:tjQwtKISFuswkQ+T3Ezwra9iMs1XtNeH3pLXS4jVZMImDRbXeypM8ctEJwqOVtBXuzakNhLVVkK2zEQ8DnnMwH+L2g8CeGBlc2HZa8iuZcoZIKrTzzqpgJB+Fkh5Nv0JP/M=,iv:MAFEU07Iio2bqwSjak7/bmgMHHm4W8RJzL2ZkpJH69I=,tag:6nkDoFMGVfs3N64sWARN8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cTFSLzRhQjlBQzNqVWxu
      RUN5eGtISXFKQ1JBSGluSWlkcUNyYjl5VUVZClZwYU95eDVlNEtqZVI5R2t5Snls
      dTVPSjdwcFlQUS93eHNNV1k1aHVKdmcKLT4gPSEtZ3JlYXNlIE02IEJbIEh4CkFq
      VUtoVUsrT0N1cDZyZ2dYbEpzWnE2YXlNQUN4UWZOd0o5TzNzTlN6MDQwSzBoTCs3
      N3VJcnRDT2pudlBLSnEKcDI0Ci0tLSA3NURFQTVCU3ZvVGpkWjFGRWd4ZzV2QXQy
      NEUxVThKSFdoM1pFQTR3Vy93CrqXyFIu3MoCHDwNnJ5KrhY75eJtxK8X/0ErOcWr
      exNx3CwNr4kgTX9M+L0SnhgnOONkb5XahfH2rkN5GXp9dgU=
      -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-08-07T12:51:59Z'
  mac: ENC[AES256_GCM,data:kLq3xueRJVH0ZSDNJageN/tKeY26v/cQSOPDnhGOu+5Ql+ONtcT6uZdPqExkcXJ2BNDAUN2x749465LAiwwHzgoqftHpnCqRGeA2Vdm6XZD/EGHkd7Wr9TNlU3+FZGGXr1RfxdiIVZKJ/Uiycp/yLNK7ACDzclmyXDhY5AUGtok=,iv:jmJxYecA90AzDPgumS2x4cN7c/1VASdCYDRhm0jq3DM=,tag:XJij55K3uR+niOgFES5oFQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
