apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-credentials
  namespace: data
  labels:
    app.kubernetes.io/part-of: shared-gitops-k8s-cluster
    gitops.microscaler.io/stack: airflow
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:bpk2d5cIzw==,iv:oTkZYr5j2gwtTxGVmmq+fqvYcNKCyKPLhbVw6As/boc=,tag:WQLFM0kwdpMaLXhFjd9pDQ==,type:str]
  password: ENC[AES256_GCM,data:ADTkoXOHz7PkN8jlnZ8ojXXZNRPv7ZK5Q4DUTE7J/88=,iv:pR/YV+ylQJWU+8ZWVpeNONLEuHwDicSk8zgIzS0D9zo=,tag:pMMwZ04LvH1JBgqZJecrCQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT3g1Mk1TYW01QW1sZytG
      SXQzQk9uOHJZVlFObmRvVUJ1UUlWb3BGa1JBCmJhRDF1bG9CMVNsNjArcUpSUEFh
      dm5HRzFvRzBLNDI0aC8xclRORnhOdEUKLT4gWEtZREh9RkgtZ3JlYXNlIHBKYUJO
      Sy8gUjoKMGFOUE5OOHJHVERvbXpRTVZjZ21idnRCZlY5WStDSktVTXZVcjVSLzE1
      ZlIKLS0tIDhta0ZkVUdoSXJMV3NXTEV0dHo2S2pYcEgxVnk1VEk3UGJaQ05CemJZ
      d3MKSUeuHzBnAqTubnLODDJY/H2Aj09eYA5Jl7gbPl23Xkv6wnjKKSJ7QnvBhme+
      SS1lq/selpjIGQ8fu6+efkcOnw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-08-07T12:51:59Z'
  mac: ENC[AES256_GCM,data:zZ1nMM30RlSjiAKhwTk68enQe7mnuTLOr+1rdhO0ZWIoxvNv7yVeH3eLXtxnxecq4qjvLRJ+mFY9xjeGfwLQgCrbswjwh8AoJ+q2CnVzVy3H9fjG1anUNYiKHe0Nxvw3tBGYXNZzGR5AO5wQ8tkY0XFgu0d9YhGJQhbKDDSTnJ8=,iv:1HhMMzNoq8Sjx/hOFtn7vH8Nmmfdzk8TKoBzNZxO23Y=,tag:4NWhWyweukfAGMgPuS9/Lw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
