apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: airflow
  labels:
    app.kubernetes.io/part-of: shared-gitops-k8s-cluster
    gitops.microscaler.io/stack: airflow
type: Opaque
stringData:
  webserver-secret-key: ENC[AES256_GCM,data:VnROIkyihqh2VYRvG5Y7nepthYrfQjigr1IOw3ojVGk=,iv:4QBn9F+4uNgUbWKZgT0PXwzi89y6eyIO7D9QlTq1aic=,tag:G7FUwuHnUspw/YB6jZvcXg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnlQREkwR0E5bVJwS0x3
      azlQRWJyNE5jdnVsaUtiNkxPaWhnT1kxQ2cwCk1Qa0tXNlo2Tjl5anhzb0V0ekFW
      K2ZrejZyN0ZzYmlBTGhLeG5tc1Y1aWMKLT4gZSldLWdyZWFzZSByQEggOjQgSCNa
      UwpENDlMbFVVUnZRcnZOeGlVNHM2UXcwQ3BSTFpIeHBrKzVyeFlEM3RQMVc1c09D
      dUlad1paUnJkTFVGUUpFV1F3CjZvdnRGUGdTRkxQOGw0S3F6MTdWV3lYd2hsMEdP
      SmhaUE1xelJYawotLS0gWW5ndVhRQ1dTOU1jNW1BWWFOWHhWU0lLMEpodm5hQmFY
      UGhOUU9jNjdSRQqefS9vfkiqJXdO8snteSYXxTTo/wmqLEWXMvtUiRIvgfNf5aMg
      lHCNxICZOUL324DW42BiuFbTSabDKhtsmX9/
      -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-08-07T12:52:00Z'
  mac: ENC[AES256_GCM,data:RwoEcC7neH9y2PYN0U1DxMyE6o89zizPchdSrxi9FP/uIsjjPxUG+wNCQFQdVV0txBwKGwdY4rFCKfLmBWehmlIOOJowz82AgNN1UYFQRG7dWXo+bmivkBKuQqRnKG5iTxN2HINya7OgWKqCi/6j2I89JuFobbUVMQE1xzBL+ZE=,iv:OxcimBytvl95pHKFzcG3Et0dmkHYEPXi2fcUwp2lJzM=,tag:aELYcmX4vfOPpH5ALv8VLQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
