apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cylon
resources:
  # Config: deployment-configuration/profiles/dev/cylon-infra (Flux profile-config)
  - deployment.yaml
  - service.yaml
