apiVersion: v1
kind: Service
metadata:
  name: routellm
  namespace: cylon
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.177.76.221"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: routellm
