apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-driver-config
    namespace: democratic-csi
    labels:
        app.kubernetes.io/part-of: shared-gitops-k8s-cluster
        gitops.microscaler.io/stack: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:2clCdaVYGf3bOK/I2Jkp0Fytatze0Wjy6IMHkV9YF/1ChLpD/KFRl/2WK4NJ/YREp9e+uJC6T+my7no8QReWWLJiB47IoX+VNh9CIAVPVufb1DnxsuMqesgdNNKFE/9yjNvAiFVoF4WC7vGEk9lshqKEkEQqhn/70+kbr/nmHA4dozE6j0Yblohn4GNWhnNreuozKV6dGVT2L8kfYEXpHM9T0tRzX1ejzVVNQkIGn7AlYaR1CnSOwzUaAlk0He7T9IwVV+5rAp2h3WTSzqlThRaMrbCgdcON43KFHe7E11sMP8Ng8+5dbyEAeGMbtLhXJ7vO9bLfwKXeCNrq/EMud3L+MgGoBuofDD7xsd7yzH5BdbIdKWKHp70D+Oul/VHKs9rCM4Td01ivztLQcp64n63eg2/HaO+CGAD3FrCURkGdxk7k4rjmlzgOOtCkjbHUzQ0+Vh4vv1gSNsvCbW017eoQ6urXPhVqfjHWv3tpXLrHuwDGwI0Mc8ZPCRwMBxtRUiY+4IAQbwOu9Tjfwr8EU6pS0prPlYt64btcsS5K1OqrC06oMlbV9tcPaRHZQZMUhrxzZt1ZPIzaI3Y64260YsEMNgIb3p36TL/0vz8fmgvpDYh7ugJLj6GMEiT/QoYitiifLMjolyXeQmbswG6wFs0pwBY4qpFPLyMT56cHw+a0Oa8dnhs9BMqGyhHz0iR05S5XxP9XtjhVhAdCG+zjPHIdoh25bIYozGylPl9x9jovBQvSvLs2/JvJTZaq9YwXjKY3iEadPeVYujRoBiZ9fohM4CZYufR+GRdOwspUiH06gOCgRR1dXBjGI52+9oraRcp+Y/LCoDmKoSV5N6mzPI/xbEraSmtYe6Yxv8KKTzcr+X2sDyFvpKvEKo69W5SRyyxJBqWvWmxdupAUy6s6wt2SKWckmYE3+mg5yNczmJmmcbQ+pF3ZtYVB8KMD0lK07/fMpYqyojJtFHkfkLPNuM3ZEg0ECG5cIxUKDf6XevFePWS9iYXkp0X1Ye6kXWpWkX+UVsfEiXS06cEBGe/zgpoT0kvg9fHUTjctl5yq6CCIj7f57Q03bvChRTn0D9Lh11AEBZqY1qajRiGsaw36jO1oqoDMyVtntukb835osp9KnVLwpaxNY8pg6M5A2HrbfVNNy4Uog0534fb0Xafav+OGjMyf0yTKQUlTaz+lAVKVSPs/h40q53Aga/3b/iEuxDZOJHbJzBEJNTrUUz3vodiq2vrevOzJfSUekSUktCkNMQkW4CnzVsn04SHErPe2yNPL1YfTUxaPUzwm3jJo6kj25IrRW81qE/oR5WyR7wUXCcMZ5gfzrWSrLqCHMQjiuFWTExlp0w7KdUxirhyyPRzy/9xroIrMcimslb7RZTmnA4+E8KUWCJH/UUfDGQWYA6GQRP8GI/mFf0zo15WlpkKAT0MDqksC1wmTFcE20crFpSmAtQ==,iv:ztYh1ZYToSLDM4EZr0JPOxFr2Y7Ye5wfJ3vkQQT2McM=,tag:HV9rlu5ti057+r+XQoNu9w==,type:str]
sops:
    age:
        - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWFF2ZVcvS0Rqc1QwTFRV
            VDM4VlNrQU9Xd3hHM1pEYU9LME1GTnpBNkhnCkwxZkRoakV5cUs1bkFqYUtBTXFH
            eU9uY1hXMWxMMEdYMFA0M05jRzhjSTQKLS0tIDBGRkprNDlHOE9UYnlXdlF2aFEv
            emg0bkRtTitkYkdIcTZwc3pEbytweVkKou9WKehzYBc0MLrSECrr4InifvVPiF8C
            VcJwwqLQS5R/Ubaz9jNCK46eK0bgZEc3czM4Izh0In2/b1KisTtl7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:16:21Z"
    mac: ENC[AES256_GCM,data:X+YraleVuSqGiXixcPMV+4X6jbfyn+fExC4AhaEExq2XYX6uw6xTiilvZ9dI4PI48n2AJejT3W+uNVVNyQKazDyleGAQd3fAm3CNj6FLb6uC3Uc2YHy1zsxvPv75ZadJANnvQ4xsfF09JMrkqv9KWvJrmD/zBQIkNpJc3b605aU=,iv:1MKgtuyLVLdbL+pd7qczuWGRdfL+gIquigL01wFm1Rs=,tag:COUxb/52d7iMqVEy2NIgFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
