# Canonical profile for democratic-csi (SMC: deployment-configuration/profiles/dev).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: democratic-csi

configMapGenerator:
  - name: democratic-csi-config
    envs:
      - application.properties

resources:
  - driver-config.secret.yaml
  - ssh-key.secret.yaml

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
