apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-ssh-key
    namespace: democratic-csi
    labels:
        app.kubernetes.io/part-of: shared-gitops-k8s-cluster
        gitops.microscaler.io/stack: democratic-csi
type: Opaque
data:
    id_ed25519: ENC[AES256_GCM,data:OmjfCCfEv4gmkAXYmwJ9c0/YJlAbhvF8Y21fyZG/0jnATeiaFK4NcezQXdRwIgRCp0zOcImSy5ZRSsayda2b+QK/YRFAICoLTYZ1vTP1LN33TSSoHvAbVv9Vkltk2ipR4FuYBrCVig3KT2zVSO2eB5cSeQqaAXzRBoghEnHTksTehJPdKtTrGP929cOmkrPGweR31HUwJLu48e4tehfl16QJj445IUklBKaR9KTzEOs7nKknlCMYgAVex16oq3+2ZK1fJ2TVeKS5vDHyQaB89ZmqI8tjH88lQ8PvOzGfCcA9UHS/ZV4zBVh8Htg7rMBNXRdGKpayJ2IshXSxiwYNxRNNVhzPIgb/L17omLsXBatGA7h8EPY5dIRhpDWtjFpIB28F5a6TcXlIiWZGUOPA2MBq8IcbLYXF4LFLfBSOldBSS7tz386cN8Ua7yOGXnGG0vbkD+T900x9GHYNv/Px1NXOivI2SxseBdSjXfW37El4I7Jh1/iJIAI1YrEjQ39k1+q8pRXMg7PTZblluj0bghZ7cdTANZzjFAF+9a8MdgauOR64OEHRZ7AwFg2tltkJ8ECrAJjicMAEy4YtlaI35Ez5QdbA2lP9Kc/S7gg1+U/tmGPM7D9tmsFRK5Cl8ZXQNEWeusY2hSrsGpoK56taE27tOAbtqJ5eOp/YejWUqg6DWbi+zbV32VOqyxVAi/pBE/vtZ4Q6VSZTZ+OTROAIj1p1ZkRddqXYcIRAByzJmsM=,iv:xExiqWeRpR1nxHH86m7nDt5xUnKP9bykFfrrxbJYMHI=,tag:n1OEmzedDVb2mGqEkEB+vA==,type:str]
sops:
    age:
        - recipient: age1lh3s2uyxrqu0u7hqgulnd43q3v0xvktukq3fcxuu6gw97uye59rqgjsd07
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZDE1NXlMU1A4NSt1S1Fs
            SDFFbGhsZnJVVzl4NnZCanIzam1JdGlXSUE0ClVaRzRnWUpVMlBHdW1jeDA4dnVJ
            SGZLak9uRDRjRjRFb1J1aDN0UWJwdkEKLS0tIFRTWStRY0JZUWc2UVh3S2ZDTmlB
            UGx4b0VjNVd6MzJpa2xTVHRHQnlLZVkKoHYZhfduZkpBMy0NH7bkQRd7Bg+My5bD
            g8tPtnZvoXB5uAGC8RUvFdmugCyQwtXpIm0+62Tyz5T0bTYbpBY6Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T08:16:21Z"
    mac: ENC[AES256_GCM,data:jy1Jx4fWCbjJs8c+aAqfGmQ8O2GvmWoA71r7B4gWBAAPqOkeJQiUFmvMP+vUro2Ce5ScI7QeBHD9TeRGb0YkGG7Ln1ekPodQBQBUJfy5DX8fVaZQjAaKEkkjAymy/tnwPmJafudUDEgQVExjaydvb1WkUDoZh9EprPr7VG6NDN0=,iv:Vnf2L0fN0l37N3UK45aVU7upJp1gxhFIbcodgp2u+Bg=,tag:q0aw5CGQsKMOvrZKrk3Mcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
